# Generated by Django 5.2.13 on 2026-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
            ],
            options={
                'verbose_name': 'Location Master',
                'verbose_name_plural': 'Location Masters',
                'ordering': ['place_name'],
            },
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='city_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
