# Generated by Django 5.2.13 on 2026-06-06 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang_app', '0002_locationmaster_kundalirecord_city_village_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmaster',
            options={'ordering': ['location_name'], 'verbose_name': 'Location Master', 'verbose_name_plural': 'Location Masters'},
        ),
        migrations.RenameField(
            model_name='locationmaster',
            old_name='place_name',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_users', to='panchang_app.locationmaster'),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='city_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='location_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
        ),
    ]
