# Generated by Django 5.2.13 on 2026-06-09 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang_app', '0003_alter_locationmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
