# Generated by Django 5.2.13 on 2026-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang_app', '0004_locationmaster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalirecord',
            name='mantra_upasana',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='phalashruti',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kundalirecord',
            name='shanti_pujan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
