# Generated by Django 5.2.13 on 2026-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang_app', '0005_kundalirecord_mantra_upasana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='category',
            field=models.CharField(choices=[('Festival', 'Festival'), ('Jayanti', 'Jayanti'), ('Punyatithi', 'Punyatithi'), ('Vrat', 'Vrat'), ('Other', 'Other')], db_index=True, default='Festival', max_length=20),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kundalirecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kundalirecord',
            name='date_of_birth',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kundalirecord',
            name='place_of_birth',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='location_name',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='shubhamuhurt',
            name='category',
            field=models.CharField(choices=[('Marriage', 'Marriage (Vivah)'), ('Gruh Pravesh', 'Gruh Pravesh'), ('Naming Ceremony', 'Naming Ceremony (Namkaran)'), ('Business', 'Business (Udyog/Vyapar)'), ('Other', 'Other Auspicious Event')], db_index=True, default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='shubhamuhurt',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
